CREATE TABLE [dbo].[ShoeSize]
(
	[ID] UNIQUEIDENTIFIER NOT NULL PRIMARY KEY, 
    [US_Size] FLOAT NOT NULL, 
    [UK_Size] FLOAT NOT NULL, 
    [EU_SIze] FLOAT NOT NULL, 
    [FootLength] FLOAT NOT NULL, 
    [GenderID] INT NOT NULL DEFAULT 0, 
    [Comment] VARCHAR(50) NULL
)
